# Generated by Django 4.2.17 on 2025-05-17 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_book_cover_image_loan_due_date_alter_review_rating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='isbn',
        ),
        migrations.AddField(
            model_name='book',
            name='isbn_encrypted',
            field=models.TextField(blank=True, null=True),
        ),
    ]
